[phases.setup]
nixPkgs = [
  "poppler_utils",
  "cairo",
  "pango",
  "glib",
  "gobject-introspection",
  "gdk-pixbuf",
  "libffi",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "shared-mime-info",
  "zlib",
]